name: her2bdl
channels:
  - conda-forge
  #- bioconda
  - sdvillal
  - defaults
dependencies:
  - python=3
  - pip
  - cudatoolkit=11.1
  - cudnn=8
  - openslide
  - h5py
  - pandas
  - xlrd
  - seaborn
  - matplotlib
  - scipy
  - numpy
  - jupyter
  - scikit-learn
  - scikit-image
  - plotly
  - pyyaml
  - openslide-python
  - pip:
    - tensorflow-gpu==2.4.1
    - twine
    - nose
    - tqdm
    - wandb
    - opencv-python
    - tensorflow-probability
    - tensorflow-datasets
    - pycm==3.0
